- name: installing software on remote
  hosts: all
  become: true
  vars:
    app: tmux
  
  tasks:
          - name: install {{ app }}
            apt:
              name: "{{ app }}"
              state: present

        