- name: installing nginx on localhost
  hosts: localhost
  become: true
  
  tasks:
          - name: install nginx
            apt:
              name: nginx
              state: present
          - name: start nginx server
            service:
              name: nginx
              state: started